SEED: 3407            # random seed
No_Bar: False        # Turn off the progressive bar

use_MPE: True
rel_pos_num: 128
str_size: 256
EVAL_SIZE: 256
min_sigma: 2.5
max_sigma: 3.25
round: 64
rezero_for_mpe: False
fix_256: True

transformer_ckpt_path: './ckpt/best_indoor_transformer.pth'
gen_weights_path0: './ckpt/LAMA_indoor/InpaintingModel_gen.pth'
dis_weights_path0: './ckpt/LAMA_indoor/InpaintingModel_dis.pth'
structure_upsample_path: './ckpt/StructureUpsampling_V5_last.pth'

train_line_path: "/train/wireframes"
eval_line_path: "/val/wireframes"

TRAIN_FLIST: data/train.txt
VAL_FLIST: data/val.txt
TEST_FLIST: data/val.txt

gt256Val_flist: 'indoor_data/GT'
gt256test_flist: 'indoor_data/GT'

TRAIN_MASK_FLIST: [ 'irregular_mask/irregular_mask_list.txt',
                    'coco_mask/coco_mask_list.txt' ]
MASK_RATE: [0.4, 0.8, 1.0]
TEST_MASK_FLIST: indoor_data/test_mask

BATCH_SIZE: 30                 # input batch size for training
INPUT_SIZE: 256               # input image size for training 0 for original size
START_ITERS: 100000             # start iters for lama
MIX_ITERS: 108000                # gradually mix the edge and line with prediction from transformer
Turning_Point: 130000            # only use the predict from transformer for edge and line
MAX_ITERS: 150000                # maximum number of iterations to train the model

SAVE_INTERVAL: 1000           # how many iterations to wait before saving model (0: never)
SAMPLE_INTERVAL: 1000         # how many iterations to wait before sampling (0: never)
SAMPLE_SIZE: 12               # number of images to sample
EVAL_INTERVAL: 2000              # how many iterations to wait before model evaluation (0: never)
LOG_INTERVAL: 1000            # how many iterations to wait before logging training status (0: never)

run_title: ''

training_model:
  kind: default
losses:
  l1:
    weight_missing: 0
    weight_known: 10
  perceptual:
    weight: 0
  adversarial:
    weight: 10
    gp_coef: 0.001
    mask_as_fake_target: true
    allow_scale_mask: true
  feature_matching:
    weight: 100
  resnet_pl:
    weight: 30
    weights_path: './'
optimizers:
  warmup_steps: 2000
  generator:
    kind: adam
    lr: 3.0e-4
  discriminator:
    kind: adam
    lr: 1.0e-4
  decay_steps: 20000
  decay_rate: 0.5

generator:
  input_nc: 4
  output_nc: 3
  ngf: 64
  n_downsampling: 3
  n_blocks: 9
  add_out_act: sigmoid
  init_conv_kwargs:
    ratio_gin: 0
    ratio_gout: 0
    enable_lfu: false
  downsample_conv_kwargs:
    ratio_gin: 0
    ratio_gout: 0
    enable_lfu: false
  resnet_conv_kwargs:
    ratio_gin: 0.75
    ratio_gout: 0.75
    enable_lfu: false
discriminator:
  input_nc: 3
